name: yolov4-cpu-track

dependencies:
  - python==3.7
  - pip
  - matplotlib
  - opencv
  - pip:
    - opencv-contrib-python==3.4.4.19
    - opencv-python==3.4.4.19
    - lxml
    - tqdm
    - tensorflow==2.3.0rc0
    - absl-py
    - easydict
    - pillow
    - pytesseract
    - onvif-zeep
    - zeep
    - pyserial